### ISSUE TITLE
BUG: blender4.1添加网格会报错

### ISSUE THREAD

**Issue by xieqsei** [WiresoulStudio/W_Mesh_28x#4]
blender4.1之后没有了自动平滑属性，在使用[W_Mesh_28x]添加网格时，有部分形状会报错。希望能有时间修复一下。

**Comment by mucrow** [comment]
@xieqsei my pull request might help you.

my second comment in the thread explains how to download my version with the fixes: https://github.com/WiresoulStudio/W_Mesh_28x/pull/5

**Comment by Milos-Feng** [comment]
> @xieqsei my pull request might help you.
> 
> my second comment in the thread explains how to download my version with the fixes: #5

Sir, I have attempted to download the latest fixed version and use Blender version 4.1.1. However, I am encountering errors when trying to create WRing and WCone. I kindly request for your assistance in resolving this issue. Thank you very much.

“Python: Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\W_Mesh_28x-fix-smooth-features\W_Ring.py", line 209, in execute
    if self.smoothed:
       ^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\blender-4.1.1-windows-x64\4.1\scripts\modules\bpy_types.py", line 939, in __getattribute__
    return super().__getattribute__(attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Make_WRing' object has no attribute 'smoothed'”

“Python: Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\W_Mesh_28x-fix-smooth-features\W_Cone.py", line 224, in execute
    if self.smoothed:
       ^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\blender-4.1.1-windows-x64\4.1\scripts\modules\bpy_types.py", line 939, in __getattribute__
    return super().__getattribute__(attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Make_WCone' object has no attribute 'smoothed'”

**Comment by mucrow** [comment]
@Milos-Feng just seems like you didn't completely uninstall the old version. try deleting it, closing blender, reopening it, and then installing my version.

**Comment by Milos-Feng** [comment]
> @Milos-Feng just seems like you didn't completely uninstall the old version. try deleting it, closing blender, reopening it, and then installing my version.

![01](https://github.com/WiresoulStudio/W_Mesh_28x/assets/174086631/723be3cc-b528-45c2-850f-bdc559bbee88)
![02](https://github.com/WiresoulStudio/W_Mesh_28x/assets/174086631/38f70a68-e1fb-418e-b433-860a704bdd6d)
![03](https://github.com/WiresoulStudio/W_Mesh_28x/assets/174086631/46236390-3229-4406-97ab-19075f3d0381)
Sir, I have reset the software and ensured that only the new version was installed. However, the problem still persists.

**Comment by mucrow** [comment]
oh, the ring primitive doesn't have a smooth parameter. that's my mistake.

**Comment by Milos-Feng** [comment]
> oh, the ring primitive doesn't have a smooth parameter. that's my mistake.
Sir, the WCone primitive does not have a smooth parameter either. It would be greatly appreciated if this could be fixed.

**Comment by Milos-Feng** [comment]
> oh, the ring primitive doesn't have a smooth parameter. that's my mistake.

Sir, the WCone primitive does not have a smooth parameter either. It would be greatly appreciated if this could be fixed.

**Comment by mucrow** [comment]
@Milos-Feng that should be fixed now if you wanna try it again

**Comment by mucrow** [comment]
also you don't gotta call me sir, it's kinda awkward for me (:    i appreciate your politeness

**Comment by Milos-Feng** [comment]
> @Milos-Feng that should be fixed now if you wanna try it again

@mucrow The addon is now functioning properly. Thank you once again for your assistance.
